theme: jekyll-theme-minimal
title: Welcome to breiger's homepage!
description: This page is for updates on my progress of turning pure javascript games into Progressive Web Apps that can be enjoyed on mobile platforms. 
